version: "3.8"
services:
  roomba_bridge:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        progress: plain
    network_mode: host
    restart: always
    privileged: true
    container_name: roomba_bridge